language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -q -r requirements.txt --use-mirrors
  - pip install -q -r requirements-dev.txt --use-mirrors
  - pip install -q -e . --use-mirrors
before_script:
  - flake8 feedhq
script:
  - createdb -U postgres
  - make test
